### ISSUE TITLE
Running tests on ARM

### ISSUE THREAD

**Issue by alban** [kinvolk/stage1-builder#11]
How difficult would it be to use our KVM stage1 to run the VM with the ARM architecture when the host (SemaphoreCI) is using x86_64?

/cc @barisione @schu

**Comment by alban** [comment]
Not so easy apparently: https://github.com/coreos/rkt/issues/3409

**Comment by schu** [comment]
From coreos/rkt#3409:

> marking as won't fix as it requires a complete overhaul of the stage0/stage1 interface, which we are not doing anytime soon.

Closing until then.
