### ISSUE TITLE
add support for Linux 4.10.1

### ISSUE THREAD

**Issue by alban** [kinvolk/stage1-builder#19]
The latest version of Linux is 4.10.1.

There are some new eBPF features according to https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md

/cc @schu @williamtu

**Comment by williamtu** [comment]
Thanks. Super useful for me!

**Comment by schu** [comment]
@williamtu Thanks :) If there's anything else you would like to have, let us know.

`kinvolk.io/aci/rkt/stage1-kvm:1.23.0,kernelversion=4.10.1` is now in the artifact store and can be used with `rkt run --insecure-options=image --stage1-name=kinvolk.io/aci/rkt/stage1-kvm:1.23.0,kernelversion=4.10.1 ...`
