### ISSUE TITLE
try new rkt version v1.26.0

### ISSUE THREAD

**Issue by alban** [kinvolk/stage1-builder#23]
stage1-builder currently uses to rkt `v1.22.0` (to fetch a patch) and to rkt `1.23.0` (dependency on the kvm ACI).

rkt has a new release https://github.com/rkt/rkt/releases/tag/v1.26.0 with option `RKT_HYPERVISOR_EXTRA_KERNEL_PARAMS=` (https://github.com/rkt/rkt/pull/3644).

We could try this one.

**Comment by schu** [comment]
Updated with https://github.com/kinvolk/stage1-builder/pull/24
