### ISSUE TITLE
CircleCI & rkt fetch

### ISSUE THREAD

**Issue by alban** [kinvolk/stage1-builder#3]
Capturing https://github.com/kinvolk/stage1-builder/pull/1#issuecomment-274869617

> - Integrate with CircleCI for automatic builds
> - Save the ACI in the CircleCI build artifact store
> - Update https://kinvolk.io/aci/ so that rkt fetch automatically fetches the ACI from the CircleCI artifact store. The manifest.tmpl.json name will need to match.

**Comment by schu** [comment]
All times are done, closing.
