### ISSUE TITLE
Missing 4.16 build

### ISSUE THREAD

**Issue by lmb** [kinvolk/stage1-builder#31]
Seems like the latest build is missing the 4.16 kernel: https://circleci.com/api/v1.1/project/github/kinvolk/stage1-builder

I must've missed something in my PR?

**Comment by schu** [comment]
Hey @lmb - the circleci setup was missing new dependencies required from Linux 4.16 on. Fixed with https://github.com/kinvolk/stage1-builder/pull/32/commits/c0efbc48ba8270667573348fbc7159a78aa1d862
